print("Hello everyone, I encountered a problem with my fist lab. \nIt sucks very bad!")
print("Dispite this problem, I did not give up on anything and I kep trying and asking for help")
print("Now i am in the process of working on it again and I think i'm figuring it out.")
print("this is the fun of codding right? It's going to be a long year \\ I think" )
print("Let me know how \nyour year, is going ")